---
githubConfigUrl: "https://github.com/voxpupuli"

runnerGroup: "voxarc"

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner@sha256:dced476aa42703ebd9aafc295ce52f160989c4528e831fc3be2aef83a1b3f6da  # 2.331.0
        command: ["/home/runner/run.sh"]
        # to be discussed
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "8000m"
            memory: "4Gi"
        volumeMounts:
          - name: hostedtoolcache
            mountPath: /opt/hostedtoolcache
          - name: work
            mountPath: /home/runner/_work
    volumes:
      - name: work
        emptyDir: {}
      - name: hostedtoolcache
        emptyDir: {}
